blank_issues_enabled: false
contact_links:
  - name: JGMaker Artist-D Facebook group
    url: https://www.facebook.com/groups/artistd
    about: Please ask and answer questions here.
  - name: JGMaker Artist-D on Discord
    url: https://discord.gg/SX7X4crNsc
    about: Join the Discord server for support and discussion.
  - name: JGMaker Videos on YouTube
    url: hhttps://www.youtube.com/playlist?list=PL1RCkPuTzWlLws3MdM0ObtQzfzQHDViCQ
    about: Tutorials and more from JGMaker users all around the world. Great for new users!
  - name: Marlin Documentation
    url: http://marlinfw.org/
    about: Lots of documentation on installing and using Marlin.
  
